integratin-test:
  stage: integratin-test
  image: "docker:${DOCKER_VERSION}"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - printenv | grep R2S2_ > /tmp/env-file
    - printenv | grep CI_JOB_STAGE >> /tmp/env-file
  script:
    - docker run --rm --env-file=/tmp/env-file -v "$R2S2_CERT":"$R2S2_CERT" "$BUILD_IMAGE_NAME" rostest ros_hackev_linetracer integratin.test
    - docker tag "$BUILD_IMAGE_NAME" "$BUILD_IMAGE_NAME_LATEST"
    - docker push "$BUILD_IMAGE_NAME_LATEST"
    - cp -rf /data/users/${R2S2_USER}/${CI_COMMIT_SHA}/${CI_JOB_STAGE}_video.mp4 .
  artifacts:
    name: "artifacts_${CI_COMMIT_SHA}"
    expire_in: 1 week
    paths:
      - ./*_video.mp4