unit-test:
  stage: unit-test
  image: "docker:${DOCKER_VERSION}"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - docker run --rm "$BUILD_IMAGE_NAME" rostest ros_hackev_linetracer default.test